name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2.11.0
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
        env:
          REACT_APP_GITHUB_URL: ${{ secrets.REACT_APP_GITHUB_URL }}
          REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}